### ISSUE TITLE
Trouble using library when installing from NPM

### ISSUE THREAD

**Issue by hydrosquall** [spotify/NFPlayerJS#15]
Based on the error message provided by Codesandbox, I suspect that maybe the `./dist` folder is missing from NPM package that results when we run `npm publish`

```
npm install nf-player
```

I tried this in 3 places ([codesandbox](https://codesandbox.io/s/mjl02rplly), [stackblitz](https://stackblitz.com/edit/react-adtdmt), and on my local environment), in all cases I was unable to build any of the pages that imported `nf-player`.

The most informative error message is from Codesandbox, as it seems to indicate that the package.json is expecting to find something under the `dist/` folder, which isn't available from NPM.

```bash
Could not fetch dependencies, please try again in a couple seconds: Something went wrong while packaging the dependency nf-player@0.6.3: ENOENT: no such file or directory, scandir '/tmp/3822393094/node_modules/nf-player/dist
```

**Comment by kirbysayshi** [comment]
Hey, sorry about that. It should all be fixed now. v0.6.5
